[tool.poetry]
name = "iredis"
version = "0.1.17"
description = "Terminal Client for Redis with AutoCompletion and Syntax Highlighting."
authors = ["laixintao <laixintao1995@163.com>"]
readme = 'README.md'
license = "MIT"
repository = 'https://github.com/laixintao/iredis'
homepage = "https://github.com/laixintao/iredis"
keywords=["Redis", "key-value store", "Commandline tools"]
classifiers = [
# see https://pypi.org/pypi?%3Aaction=list_classifiers
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Environment :: Console :: Curses",
    "Environment :: MacOS X",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Topic :: Database",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
]
include = ["command_syntax.csv", "commands.json"]

[tool.poetry.dependencies]
python = "^3.7"
redis = "^3"
prompt_toolkit = "^2"
Pygments = "^2"
click8 = "^8"

[tool.poetry.dev-dependencies]
pytest = "^5"
requests = "^2"
lxml = "^4"
pexpect = "^4.7"
flake8 = "^3.7"

[tool.poetry.scripts]
iredis = 'iredis.entry:main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
